[package]
name = "ising"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bit-vec = "0.8.0"
itertools = "0.14.0"
noisy_float = "0.2.0"
plotters = "0.3.7"
priority-queue = "2.1.1"
rand = "0.9.0"
rand_distr = "0.5.0"
rand_pcg = "0.9.0"

